name: Setup frontend
description: Setup Node.js and install frontend dependencies
inputs:
  node-version:
    description: Node.js version
    required: false
    default: '18'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      shell: bash
      run: npm ci
      working-directory: frontend
