name: Setup backend
description: Setup Python and install backend dependencies
inputs:
  python-version:
    description: Python version
    required: false
    default: '3.11'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: backend/requirements.txt

    - name: Install backend dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend
